insert into pais (codigo,descricao) values('132','Afeganistão');
insert into pais (codigo,descricao) values('7560','África do Sul');
insert into pais (codigo,descricao) values('175','Albânia, República da');
insert into pais (codigo,descricao) values('230','Alemanha');
insert into pais (codigo,descricao) values('370','Andorra');
insert into pais (codigo,descricao) values('400','Angola');
insert into pais (codigo,descricao) values('418','Anguilla');
insert into pais (codigo,descricao) values('434','Antigua e Barbuda');
insert into pais (codigo,descricao) values('477','Antilhas Holandesas');
insert into pais (codigo,descricao) values('531','Arábia Saudita');
insert into pais (codigo,descricao) values('590','Argélia');
insert into pais (codigo,descricao) values('639','Argentina');
insert into pais (codigo,descricao) values('647','Armênia, República da');
insert into pais (codigo,descricao) values('655','Aruba');
insert into pais (codigo,descricao) values('698','Austrália');
insert into pais (codigo,descricao) values('728','Áustria');
insert into pais (codigo,descricao) values('736','Azerbaijão, República do');
insert into pais (codigo,descricao) values('779','Bahamas, Ilhas');
insert into pais (codigo,descricao) values('809','Bahrein, Ilhas');
insert into pais (codigo,descricao) values('817','Bangladesh');
insert into pais (codigo,descricao) values('833','Barbados');
insert into pais (codigo,descricao) values('850','Belarus');
insert into pais (codigo,descricao) values('876','Bélgica');
insert into pais (codigo,descricao) values('884','Belize');
insert into pais (codigo,descricao) values('2291','Benin');
insert into pais (codigo,descricao) values('906','Bermudas');
insert into pais (codigo,descricao) values('973','Bolívia');
insert into pais (codigo,descricao) values('981','Bósnia-Herzegovina');
insert into pais (codigo,descricao) values('1015','Botsuana');
insert into pais (codigo,descricao) values('1058','Brasil');
insert into pais (codigo,descricao) values('1082','Brunei');
insert into pais (codigo,descricao) values('1112','Bulgária, República da');
insert into pais (codigo,descricao) values('310','Burkina Faso');
insert into pais (codigo,descricao) values('1155','Burundi');
insert into pais (codigo,descricao) values('1198','Butão');
insert into pais (codigo,descricao) values('1279','Cabo Verde, República de');
insert into pais (codigo,descricao) values('1457','Camarões');
insert into pais (codigo,descricao) values('1414','Camboja');
insert into pais (codigo,descricao) values('1490','Canadá');
insert into pais (codigo,descricao) values('1504','Canal, Ilhas do (Jersey e Guernsey)');
insert into pais (codigo,descricao) values('1511','Canárias, Ilhas');
insert into pais (codigo,descricao) values('1546','Catar');
insert into pais (codigo,descricao) values('1376','Cayman, Ilhas');
insert into pais (codigo,descricao) values('1538','Cazaquistão, República do');
insert into pais (codigo,descricao) values('7889','Chade');
insert into pais (codigo,descricao) values('1589','Chile');
insert into pais (codigo,descricao) values('1600','China, República Popular da');
insert into pais (codigo,descricao) values('1635','Chipre');
insert into pais (codigo,descricao) values('5118','Christmas, Ilha (Navidad)');
insert into pais (codigo,descricao) values('7412','Cingapura');
insert into pais (codigo,descricao) values('1651','Cocos (Keeling), Ilhas');
insert into pais (codigo,descricao) values('1694','Colômbia');
insert into pais (codigo,descricao) values('1732','Comores, Ilhas');
insert into pais (codigo,descricao) values('8885','Congo, República Democrática do');
insert into pais (codigo,descricao) values('1775','Congo, República do');
insert into pais (codigo,descricao) values('1830','Cook, Ilhas');
insert into pais (codigo,descricao) values('1872','Coréia, Rep. Pop. Democrática da');
insert into pais (codigo,descricao) values('1902','Coréia, República da');
insert into pais (codigo,descricao) values('1937','Costa do Marfim');
insert into pais (codigo,descricao) values('1961','Costa Rica');
insert into pais (codigo,descricao) values('1988','Coveite');
insert into pais (codigo,descricao) values('1953','Croácia, República da');
insert into pais (codigo,descricao) values('1996','Cuba');
insert into pais (codigo,descricao) values('2321','Dinamarca');
insert into pais (codigo,descricao) values('7838','Djibuti');
insert into pais (codigo,descricao) values('2356','Dominica, Ilha');
insert into pais (codigo,descricao) values('2402','Egito');
insert into pais (codigo,descricao) values('6874','El Salvador');
insert into pais (codigo,descricao) values('2445','Emirados Árabes Unidos');
insert into pais (codigo,descricao) values('2399','Equador');
insert into pais (codigo,descricao) values('2437','Eritréia');
insert into pais (codigo,descricao) values('6289','Escócia');
insert into pais (codigo,descricao) values('2470','Eslovaca, República');
insert into pais (codigo,descricao) values('2461','Eslovênia, República da');
insert into pais (codigo,descricao) values('2453','Espanha');
insert into pais (codigo,descricao) values('2496','Estados Unidos');
insert into pais (codigo,descricao) values('2518','Estônia, República da');
insert into pais (codigo,descricao) values('2534','Etiópia');
insert into pais (codigo,descricao) values('2550','Falkland (Ilhas Malvinas)');
insert into pais (codigo,descricao) values('2593','Feroe, Ilhas');
insert into pais (codigo,descricao) values('8702','Fiji');
insert into pais (codigo,descricao) values('2674','Filipinas');
insert into pais (codigo,descricao) values('2712','Finlândia');
insert into pais (codigo,descricao) values('1619','Formosa (Taiwan)');
insert into pais (codigo,descricao) values('2755','França');
insert into pais (codigo,descricao) values('2810','Gabão');
insert into pais (codigo,descricao) values('6289','Gales, País de');
insert into pais (codigo,descricao) values('2852','Gâmbia');
insert into pais (codigo,descricao) values('2895','Gana');
insert into pais (codigo,descricao) values('2917','Geórgia, República da');
insert into pais (codigo,descricao) values('2933','Gibraltar');
insert into pais (codigo,descricao) values('6289','Grã-Bretanha');
insert into pais (codigo,descricao) values('2976','Granada');
insert into pais (codigo,descricao) values('3018','Grécia');
insert into pais (codigo,descricao) values('3050','Groenlândia');
insert into pais (codigo,descricao) values('3093','Guadalupe');
insert into pais (codigo,descricao) values('3131','Guam');
insert into pais (codigo,descricao) values('3174','Guatemala');
insert into pais (codigo,descricao) values('3379','Guiana');
insert into pais (codigo,descricao) values('3255','Guiana Francesa');
insert into pais (codigo,descricao) values('3298','Guiné');
insert into pais (codigo,descricao) values('3344','Guiné-Bissau');
insert into pais (codigo,descricao) values('3310','Guiné-Equatorial');
insert into pais (codigo,descricao) values('3417','Haiti');
insert into pais (codigo,descricao) values('5738','Holanda (Países Baixos)');
insert into pais (codigo,descricao) values('3450','Honduras');
insert into pais (codigo,descricao) values('3514','Hong Kong, Região Adm. Especial');
insert into pais (codigo,descricao) values('3557','Hungria, República da');
insert into pais (codigo,descricao) values('3573','Iêmen');
insert into pais (codigo,descricao) values('3611','Índia');
insert into pais (codigo,descricao) values('3654','Indonésia');
insert into pais (codigo,descricao) values('6289','Inglaterra');
insert into pais (codigo,descricao) values('3727','Irã, República Islâmica do');
insert into pais (codigo,descricao) values('3697','Iraque');
insert into pais (codigo,descricao) values('3751','Irlanda');
insert into pais (codigo,descricao) values('6289','Irlanda do Norte');
insert into pais (codigo,descricao) values('3794','Islândia');
insert into pais (codigo,descricao) values('3832','Israel');
insert into pais (codigo,descricao) values('3867','Itália');
insert into pais (codigo,descricao) values('3883','Iugoslávia, República Fed. da');
insert into pais (codigo,descricao) values('3913','Jamaica');
insert into pais (codigo,descricao) values('3999','Japão');
insert into pais (codigo,descricao) values('3964','Johnston, Ilhas');
insert into pais (codigo,descricao) values('4030','Jordânia');
insert into pais (codigo,descricao) values('4111','Kiribati');
insert into pais (codigo,descricao) values('4200','Laos, Rep. Pop. Democrática do');
insert into pais (codigo,descricao) values('4235','Lebuan');
insert into pais (codigo,descricao) values('4260','Lesoto');
insert into pais (codigo,descricao) values('4278','Letônia, República da');
insert into pais (codigo,descricao) values('4316','Líbano');
insert into pais (codigo,descricao) values('4340','Libéria');
insert into pais (codigo,descricao) values('4383','Líbia');
insert into pais (codigo,descricao) values('4405','Liechtenstein');
insert into pais (codigo,descricao) values('4421','Lituânia, República da');
insert into pais (codigo,descricao) values('4456','Luxemburgo');
insert into pais (codigo,descricao) values('4472','Macau');
insert into pais (codigo,descricao) values('4499','Macedônia');
insert into pais (codigo,descricao) values('4502','Madagascar');
insert into pais (codigo,descricao) values('4525','Madeira, Ilha da');
insert into pais (codigo,descricao) values('4553','Malásia');
insert into pais (codigo,descricao) values('4588','Malavi');
insert into pais (codigo,descricao) values('4618','Maldivas');
insert into pais (codigo,descricao) values('4642','Máli');
insert into pais (codigo,descricao) values('4677','Malta');
insert into pais (codigo,descricao) values('3595','Man, Ilhas');
insert into pais (codigo,descricao) values('4723','Marianas do Norte');
insert into pais (codigo,descricao) values('4740','Marrocos');
insert into pais (codigo,descricao) values('4766','Marshall, Ilhas');
insert into pais (codigo,descricao) values('4774','Martinica');
insert into pais (codigo,descricao) values('4855','Maurício');
insert into pais (codigo,descricao) values('4880','Mauritânia');
insert into pais (codigo,descricao) values('4936','México');
insert into pais (codigo,descricao) values('930','Mianmar (Birmânia)');
insert into pais (codigo,descricao) values('4995','Micronésia');
insert into pais (codigo,descricao) values('4901','Midway, Ilhas');
insert into pais (codigo,descricao) values('5053','Moçambique');
insert into pais (codigo,descricao) values('4944','Moldávia, República da');
insert into pais (codigo,descricao) values('4952','Mônaco');
insert into pais (codigo,descricao) values('4979','Mongólia');
insert into pais (codigo,descricao) values('5010','Montserrat, Ilhas');
insert into pais (codigo,descricao) values('5070','Namíbia');
insert into pais (codigo,descricao) values('5088','Nauru');
insert into pais (codigo,descricao) values('5177','Nepal');
insert into pais (codigo,descricao) values('5215','Nicarágua');
insert into pais (codigo,descricao) values('5258','Niger');
insert into pais (codigo,descricao) values('5282','Nigéria');
insert into pais (codigo,descricao) values('5312','Niue, Ilha');
insert into pais (codigo,descricao) values('5355','Norfolk, Ilha');
insert into pais (codigo,descricao) values('5380','Noruega');
insert into pais (codigo,descricao) values('5428','Nova Caledônia');
insert into pais (codigo,descricao) values('5487','Nova Zelândia');
insert into pais (codigo,descricao) values('5568','Omã');
insert into pais (codigo,descricao) values('5738','Países Baixos (Holanda)');
insert into pais (codigo,descricao) values('5754','Palau');
insert into pais (codigo,descricao) values('5800','Panamá');
insert into pais (codigo,descricao) values('5452','Papua Nova Guiné');
insert into pais (codigo,descricao) values('5762','Paquistão');
insert into pais (codigo,descricao) values('5860','Paraguai');
insert into pais (codigo,descricao) values('5894','Peru');
insert into pais (codigo,descricao) values('5932','Pitcairn, Ilha');
insert into pais (codigo,descricao) values('5991','Polinésia Francesa');
insert into pais (codigo,descricao) values('6033','Polônia, República da');
insert into pais (codigo,descricao) values('6114','Porto Rico');
insert into pais (codigo,descricao) values('6076','Portugal');
insert into pais (codigo,descricao) values('6238','Quênia');
insert into pais (codigo,descricao) values('6254','Quirguiz, República');
insert into pais (codigo,descricao) values('6289','Reino Unido');
insert into pais (codigo,descricao) values('6408','República Centro-Africana');
insert into pais (codigo,descricao) values('6475','República Dominicana');
insert into pais (codigo,descricao) values('6602','Reunião, Ilha');
insert into pais (codigo,descricao) values('6700','Romênia');
insert into pais (codigo,descricao) values('6750','Ruanda');
insert into pais (codigo,descricao) values('6769','Rússia');
insert into pais (codigo,descricao) values('6858','Saara Ocidental');
insert into pais (codigo,descricao) values('6777','Salomão, Ilhas');
insert into pais (codigo,descricao) values('6904','Samoa');
insert into pais (codigo,descricao) values('6912','Samoa Americana');
insert into pais (codigo,descricao) values('6971','San Marino');
insert into pais (codigo,descricao) values('7102','Santa Helena');
insert into pais (codigo,descricao) values('7153','Santa Lúcia');
insert into pais (codigo,descricao) values('6955','São Cristóvão e Neves');
insert into pais (codigo,descricao) values('7005','São Pedro e Miquelon');
insert into pais (codigo,descricao) values('7200','São Tomé e Príncipe, Ilhas');
insert into pais (codigo,descricao) values('7056','São Vicente e Granadinas');
insert into pais (codigo,descricao) values('7285','Senegal');
insert into pais (codigo,descricao) values('7358','Serra Leoa');
insert into pais (codigo,descricao) values('7315','Seychelles');
insert into pais (codigo,descricao) values('7447','Síria, República Árabe da');
insert into pais (codigo,descricao) values('7480','Somália');
insert into pais (codigo,descricao) values('7501','Sri Lanka');
insert into pais (codigo,descricao) values('7544','Suazilândia');
insert into pais (codigo,descricao) values('7595','Sudão');
insert into pais (codigo,descricao) values('7641','Suécia');
insert into pais (codigo,descricao) values('7676','Suíça');
insert into pais (codigo,descricao) values('7706','Suriname');
insert into pais (codigo,descricao) values('7722','Tadjiquistão');
insert into pais (codigo,descricao) values('7765','Tailândia');
insert into pais (codigo,descricao) values('7803','Tanzânia, República Unida da');
insert into pais (codigo,descricao) values('7919','Tcheca, República');
insert into pais (codigo,descricao) values('7820','Território Britânico Oc. Índico');
insert into pais (codigo,descricao) values('7951','Timor Leste');
insert into pais (codigo,descricao) values('8001','Togo');
insert into pais (codigo,descricao) values('8109','Tonga');
insert into pais (codigo,descricao) values('8052','Toquelau, Ilhas');
insert into pais (codigo,descricao) values('8150','Trinidad e Tobago');
insert into pais (codigo,descricao) values('8206','Tunísia');
insert into pais (codigo,descricao) values('8230','Turcas e Caicos, Ilhas');
insert into pais (codigo,descricao) values('8249','Turcomenistão, República do');
insert into pais (codigo,descricao) values('8273','Turquia');
insert into pais (codigo,descricao) values('8281','Tuvalu');
insert into pais (codigo,descricao) values('8311','Ucrânia');
insert into pais (codigo,descricao) values('8338','Uganda');
insert into pais (codigo,descricao) values('8451','Uruguai');
insert into pais (codigo,descricao) values('8478','Uzbequistão, República do');
insert into pais (codigo,descricao) values('5517','Vanuatu');
insert into pais (codigo,descricao) values('8486','Vaticano, Estado da Cidade do');
insert into pais (codigo,descricao) values('8508','Venezuela');
insert into pais (codigo,descricao) values('8583','Vietnã');
insert into pais (codigo,descricao) values('8630','Virgens, Ilhas (Britânicas)');
insert into pais (codigo,descricao) values('8664','Virgens, Ilhas (E.U.A.)');
insert into pais (codigo,descricao) values('8737','Wake, Ilha');
insert into pais (codigo,descricao) values('8753','Wallis e Futuna, Ilhas');
insert into pais (codigo,descricao) values('8907','Zâmbia');
insert into pais (codigo,descricao) values('6653','Zimbábue');
insert into pais (codigo,descricao) values('8958','Zona do Canal do Panamá');
