CREATE TABLE `filial` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `Id_empresa` bigint(20) NOT NULL,
  `codigo_filial` bigint(20) DEFAULT NULL,
  `codigo_filial_integracao` varchar(20) COLLATE latin1_general_cs DEFAULT NULL,
  `cnpj` varchar(20) COLLATE latin1_general_cs NOT NULL,
  `razao_social` varchar(60) COLLATE latin1_general_cs NOT NULL,
  `nome_fantasia` varchar(50) COLLATE latin1_general_cs NOT NULL,
  `logradouro` varchar(6) COLLATE latin1_general_cs DEFAULT NULL,
  `endereco` varchar(60) COLLATE latin1_general_cs DEFAULT NULL,
  `endereco_numero` varchar(10) COLLATE latin1_general_cs DEFAULT NULL,
  `complemento` varchar(60) COLLATE latin1_general_cs DEFAULT NULL,
  `bairro` varchar(30) COLLATE latin1_general_cs DEFAULT NULL,
  `cidade` varchar(40) COLLATE latin1_general_cs DEFAULT NULL,
  `estado` char(2) CHARACTER SET latin1 DEFAULT NULL,
  `cep` varchar(10) COLLATE latin1_general_cs DEFAULT NULL,
  `codigo_pais` varchar(4) COLLATE latin1_general_cs DEFAULT NULL,
  `data_adesao_sn` date DEFAULT NULL,
  `telefone1_ddd` varchar(5) COLLATE latin1_general_cs DEFAULT NULL,
  `telefone1_numero` varchar(15) COLLATE latin1_general_cs DEFAULT NULL,
  `telefone2_ddd` varchar(5) COLLATE latin1_general_cs DEFAULT NULL,
  `telefone2_numero` varchar(15) COLLATE latin1_general_cs DEFAULT NULL,
  `fax_ddd` varchar(5) COLLATE latin1_general_cs DEFAULT NULL,
  `fax_numero` varchar(15) COLLATE latin1_general_cs DEFAULT NULL,
  `email` varchar(100) COLLATE latin1_general_cs DEFAULT NULL,
  `website` varchar(100) COLLATE latin1_general_cs DEFAULT NULL,
  `cnae` varchar(10) COLLATE latin1_general_cs DEFAULT NULL,
  `cnae_municipal` varchar(10) COLLATE latin1_general_cs DEFAULT NULL,
  `inscricao_estadual` varchar(20) COLLATE latin1_general_cs DEFAULT NULL,
  `inscricao_municipal` varchar(20) COLLATE latin1_general_cs DEFAULT NULL,
  `inscricao_suframa` varchar(20) COLLATE latin1_general_cs DEFAULT NULL,
  `regime_tributario` tinyint(4) DEFAULT NULL,
  `inativa` char(1) COLLATE latin1_general_cs DEFAULT NULL,
  `gera_nfse` char(1) COLLATE latin1_general_cs DEFAULT NULL,
  `optante_simples_nacional` char(1) COLLATE latin1_general_cs DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs COMMENT='tabela de cadastro da filial';

CREATE TABLE `filial_logo` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `id_filial` bigint(20) NOT NULL,
  `imagem` blob,
  PRIMARY KEY (`Id`),
  KEY `fk_filial_logo_filial` (`Id_filial`),
  CONSTRAINT `fk_filial_logo_filial` FOREIGN KEY (`Id_filial`) REFERENCES `filial` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;
